"""Add rag_documents table for RBAC

Revision ID: aa376f4a6cc4
Revises: 9d1901b3d623
Create Date: 2025-12-01 17:08:39.925702

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa376f4a6cc4"
down_revision: Union[str, Sequence[str], None] = "9d1901b3d623"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rag_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rag_documents_filename"), "rag_documents", ["filename"], unique=False
    )
    op.create_index(
        op.f("ix_rag_documents_user_id"), "rag_documents", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rag_documents_user_id"), table_name="rag_documents")
    op.drop_index(op.f("ix_rag_documents_filename"), table_name="rag_documents")
    op.drop_table("rag_documents")
    # ### end Alembic commands ###
